export const testFeeds = [
    {title:"Ars Technica", url:"http://feeds.arstechnica.com/arstechnica/index/"}, 
    {title:"Slashdot", url:"http://rss.slashdot.org/Slashdot/slashdot"}, 
    {title:"TorrentFreak", url:"http://feed.torrentfreak.com/Torrentfreak"}, 
    {title:"CSS-Tricks", url:"http://feeds.feedburner.com/CssTricks"}, 
    {title:"Laughing Squid", url:"http://feeds.laughingsquid.com/laughingsquid"}, 
    {title:" feuilleton ", url:"http://www.johncoulthart.com/feuilleton/feed/"}, 
    {title:"Abduzeedo", url:"http://abduzeedo.com/rss.xml"}, 
    {title:"HeyDesigner", url:"http://heydesigner.com/feed/"}, 
    {title:"xkcd.com", url:"https://xkcd.com/atom.xml"}, 
    {title:"iGNANT.com", url:"http://feeds.feedburner.com/ignant?format=xml"}, 
    {title:"The Intercept", url:"https://firstlook.org/theintercept/feed/?rss"}, 
    {title:"LensCulture", url:"https://www.lensculture.com/feeds/feed.rss"}, 
    {title:"helly cherry", url:"http://www.hellycherry.com/feeds/posts/default"}, 
    {title:"WebdesignerNews", url:"http://www.webdesignernews.com/rss"}, 
    {title:"Boing Boing", url:"https://boingboing.net/feed"}, 
    {title:"Typewolf", url:"https://www.typewolf.com/feed"}, 
    {title:"Typewolf Blog", url:"https://www.typewolf.com/blog/feed"}, 
    {title:"Smashing Magazine", url:"https://www.smashingmagazine.com/feed/"}, 
    {title:"We Make Money Not Art", url:"http://we-make-money-not-art.com/feed/"}, 
    {title:"UX Planet", url:"https://uxplanet.org/feed"}, 
    {title:"FUJILOVE MAGAZINE", url:"https://fujilove.com/feed/"}, 
    {title:"The Atlantic", url:"https://www.theatlantic.com/feed/best-of/"}, 
    {title:"Muzli", url:"https://medium.muz.li/feed"}, 
    {title:"Sidebar", url:"https://sidebar.io/feed.xml"}, 
    {title:"Digital Synopsis", url:"https://digitalsynopsis.com/feed/"}, 
    {title:"Wired", url:"https://www.wired.com/feed/rss"}, 
    {title:"Atlas Obscura", url:"https://www.atlasobscura.com/feeds/latest"}, 
    {title:"Street Photography Magazine", url:"https://streetphotographymagazine.com/feed/"}, 
    {title:"My Modern Met", url:"https://mymodernmet.com/feed/"}, 
    {title:"Mother Jones", url:"https://www.motherjones.com/feed/"}, 
    {title:"Witness", url:"https://witness.worldpressphoto.org/feed"}, 
    {title:"CSS In Real Life", url:"https://css-irl.info/rss.xml"}, 
    {title:"Futurism", url:"https://futurism.com/feed"}, 
    {title:"Quincy Larson", url:"https://www.freecodecamp.org/news/rss/"}, 
    {title:"Space.com", url:"https://www.space.com/feeds/all"}, 
    {title:"CineVue", url:"https://cine-vue.com/feed"}, 
    {title:"A List Apart", url:"https://alistapart.com/main/feed/"}, 
    {title:"Better Web Type", url:"https://betterwebtype.com/feed.xml"}, 
    {title:"Dan u Beogradu", url:"https://www.danubeogradu.rs/feed/"}, 
    {title:"Vitraž", url:"https://www.vitraz.net/feed/"}, 
    {title:"Talas.rs", url:"https://talas.rs/feed/"}, 
    {title:"Balkanrock.com", url:"https://balkanrock.com/feed/"}, 
    {title:"Typ.io", url:"https://typ.io/samples.rss"}, 
    {title:"Klub putnika", url:"http://www.klubputnika.org/?view=klubputnika&amp;format=feed&amp;type=rss"}, 
    {title:"WARREN ELLIS LTD", url:"https://warrenellis.ltd/feed/"}, 
    {title:"Fujifilm X-Photography", url:"https://www.f16.click/feed/"}, 
    {title:"Bruce Sterling", url:"https://brucesterling.tumblr.com/rss"}, 
    {title:"Snežana Radojičić", url:"http://www.snezanaradojicic.com/feed/"}, 
    {title:"The 8 Street", url:"https://the8street.com/work?format=rss"}, 
    {title:"Pluralistic", url:"https://pluralistic.net/feed/"}, 
    {title:"MIT Technology Review", url:"https://www.technologyreview.com/feed/"}, 
    {title:"Oblakoder", url:"https://www.oblakoder.org.rs/feed/"}, 
    {title:"Jason Fried", url:"https://world.hey.com/jason/feed.atom"}, 
    {title:"Kaldrma", url:"https://kaldrma.rs/feed/"}, 
    {title:"Interconnected", url:"https://interconnected.org/home/feed"}, 
    {title:"Lazar's Bin", url:"https://bin.fuzzylogic.ltd/feed.xml"}, 
    {title:"Yancey Strickler", url:"https://ystrickler.com/feed/"}, 
    {title:"404 Media", url:"https://www.404media.co/rss/"}, 
    {title:"overreacted — A blog by Dan Abramov", url:"https://overreacted.io/atom.xml" }
]